### ISSUE TITLE
minor dependency install error

### ISSUE THREAD

**Issue by gojimmypi** [tomverbeure/vexriscv_ocd_blog#1]
The [blog instructions](https://tomverbeure.github.io/2021/07/18/VexRiscv-OpenOCD-and-Traps.html) for "_Compiling the Custom OpenOCD Version_" has this line:

```
sudo apt install libtool automake libusb-1.0.0-dev texinfo libusb-dev libyaml-dev pkg-config
```
that gives an error:
```
E: Unable to locate package libusb-1.0.0-dev
E: Couldn't find any package by glob 'libusb-1.0.0-dev'
```
I think it should be:
```
sudo apt install libtool automake libusb-1.0-0-dev texinfo libusb-dev libyaml-dev pkg-config
```

(libusb-1.0`-`0-dev _instead of_ libusb-1.0`.`0-dev)

edit: also the original install is to `/opt/openocd_vex/bin/openocd ` but later there is reference to `/opt/openocd-vex/bin/openocd`  

(openocd`_`vex vs openocd`-`vex)

**Comment by tomverbeure** [comment]
> (libusb-1.0-0-dev instead of libusb-1.0.0-dev)
Fixed.

I have no idea how such a typo could have happened!

>  edit: also the original install is to /opt/openocd_vex/bin/openocd but later there is reference to /opt/openocd-vex/bin/openocd

Also fixed. I used to have _vex and -vex on different machines and recently made it all _vex...

Thanks!
Tom
