### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hparpinel** [tomverbeure/vexriscv_ocd_blog#2]
I would like to know how you generated the bitstreams in the folders quartus_max10_deca and quartus_max10_deca_semi. Are the file src in this repository?

Thank you,
Hellen

**Comment by tomverbeure** [comment]
Yes, all the source code is included.

To recreate the bitstream, you need to load the project QPF file into Quartus.

The QSF file loads the 2 RTL files:

https://github.com/tomverbeure/vexriscv_ocd_blog/blob/5af8f261589db692b2ce09fe957c9987ed52d527/quartus_max10_deca/vexriscv_ocd.qsf#L52-L53

**Comment by hparpinel** [comment]
Thank you for answering my question. I have a few other questions. Do you have a discord channel that I can reach out to you thru if possible?

~Hellen

**Comment by tomverbeure** [comment]
My DMs are open on Twitter.
